Add a ContainerViewController subspec
BottleRocketStudios/iOS-UtiliKit pull request #2
Opened 2018-01-02 21:57 UTC by wmcginty

Added a container view controller. Doesn't present any visuals for navigation of it's own, just the child view controllers. Can probably write some unit tests for parts of the functionality.

2018-01-24 22:59 UTC, wmcginty commented
@BottleRocketStudios/ios-developers Please take a look at this when you get a chance.

2018-01-24 23:31 UTC, ganttastic approved these changes
Looks good to me. ContainerViewController looks nice!

2018-02-02 21:07 UTC, tylermilner requested changes
Looks cool! Just a few minor fixes needed I think.

2018-02-02 21:07 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerTransitionContext.swift
> +        viewControllers = [UITransitionContextViewControllerKey.from : sourceViewController,
I think you can use type inference here, right?
```
viewControllers = [.from : sourceViewController,
                   .to : destinationViewController]
```

2018-02-02 21:07 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerTransitionContext.swift
> +        return CGAffineTransform.identity
Can use type inference here as well.
```
return .identity
```

2018-02-02 21:07 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +    public private(set) var isTransitioning: Bool = false
`public` `private`?

2018-02-02 21:07 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +    open func transitionToController(withTitle title: String) {
Is this an API we want as part of this library? Since titles are susceptible to changing from UX, it seems like we wouldn't be doing anyone a service if we gave them the option to use this in production code. We may want to declare this part of the extension in the Example code instead.

2018-02-02 21:07 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +        source.map { removeSourceControllerFromContainer($0, animated: animated) }
Nice uses of `map` and `flatMap` in here!

2018-02-02 21:09 UTC, wmcginty commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +    public private(set) var isTransitioning: Bool = false
Public getter, private setter. Not sure exactly how valuable it is to an outside component - but assumed it couldn't hurt.

2018-02-02 21:09 UTC, wmcginty commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +    open func transitionToController(withTitle title: String) {
Fair point. Will change.

2018-02-02 21:14 UTC, wmcginty commented
@tylermilner Requested changes have been made

2018-02-02 21:37 UTC, tylermilner commented on UtiliKit/Classes/Container/ContainerViewController.swift
> +    public private(set) var isTransitioning: Bool = false
Ah, I forgot this is a framework so it just looked like a typo at first.

2018-02-02 21:39 UTC, tylermilner approved these changes

2018-02-02 22:07 UTC, merged